apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 179460961317.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 179460961317.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 87bad727
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
